name: Deployment

on:
  workflow_run:
    workflows: ["CI"]  
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get the image tag from the CI workflow
        id: get_image_tag
        run: echo "IMAGE_TAG=${{ github.event.workflow_run.outputs.image_tag }}" >> $GITHUB_ENV

      - name: Deploy Docker image to server
        run: |
          echo "Using image tag: $IMAGE_TAG"
          ssh -o StrictHostKeyChecking=no ubuntu@13.233.83.92 << 'EOF'
            # Stop and remove the existing container if it exists
            docker stop java-app || true
            docker rm java-app || true
            
            # Pull the latest Docker image from Docker Hub
            docker pull ckdh0799/java-app:$IMAGE_TAG
            
            # Run the new Docker container
            docker run -itd --name java-app -p 800:8080 ckdh0799/java-app:$IMAGE_TAG
          EOF
