name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        id: build
        run: |
          TAG="version${GITHUB_RUN_NUMBER}"  
          echo "Building Docker image with tag: $TAG"
          docker build -t ckdh0799/java-app:$TAG .

      - name: Push the Docker image
        run: |
          TAG="version${GITHUB_RUN_NUMBER}"
          echo "Pushing image with tag: $TAG"
          docker push ckdh0799/java-app:$TAG
