name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t ckdh0799/java-app:version"${GITHUB_RUN_NUMBER}" .

      - name: Push the Docker image
        run: |
          docker push ckdh0799/java-app:version"${GITHUB_RUN_NUMBER}"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
      - name: Deploy Docker image to server
        run: |   
          ssh -o StrictHostKeyChecking=no ubuntu@13.200.254.232 << 'EOF'
            # Stop and remove the existing container if it exists
            docker stop java-app || true
            docker rm java-app || true
            
            # Pull the latest Docker image from Docker Hub
            docker pull ckdh0799/java-app:version"${GITHUB_RUN_NUMBER}
            
            # Run the new Docker container
            docker run -itd --name java-app -p 800:8080 ckdh0799/java-app:version"${GITHUB_RUN_NUMBER}
          EOF
