name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust this if your main branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2      

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ckdh0799/java-app:${{ github.run_number }} .

      - name: Push Docker image
        run: |
          docker push ckdh0799/java-app:${{ github.run_number }}


      - name: SSH into server and run container
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ckdh0799/java-app:${{ github.run_number }}
            docker stop java-app || true  # Stop the old container if it exists
            docker rm java-app || true  # Remove the old container
            docker run -d --name java-app -p 800:8080 ckdh0799/java-app:${{ github.run_number }}
